//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoQuestion
    {
        public int DemoQuestionID { get; set; }
        public int DemoID { get; set; }
        public int WizardQuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual Demo Demo { get; set; }
        public virtual WizardQuestion WizardQuestion { get; set; }
    }
}
