//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public short DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string DistrictShortName { get; set; }
        public Nullable<int> DepartmentKey { get; set; }
        public Nullable<int> DistrictKey { get; set; }
        public Nullable<int> EdStatsSort { get; set; }
        public string Type { get; set; }
        public Nullable<short> County { get; set; }
        public string SLC { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EdenInclude { get; set; }
        public Nullable<int> NcesAgencyID { get; set; }
        public Nullable<byte> NcesAgencyType { get; set; }
        public Nullable<int> NcesFIPSCnty { get; set; }
        public string NcesGradeSpan { get; set; }
        public Nullable<byte> NcesOpStatus { get; set; }
        public string NcesPhone { get; set; }
        public string PEI_User { get; set; }
        public string WebAddress { get; set; }
        public string Email { get; set; }
        public string DirectoryInclusion { get; set; }
        public string RouterIP { get; set; }
        public Nullable<float> FRLunchPct { get; set; }
        public string Title1Eligible { get; set; }
        public string Title3 { get; set; }
        public string McK_Vinto { get; set; }
        public string Act { get; set; }
        public string SchoolYear { get; set; }
        public string Accountability { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string ChangeUser { get; set; }
        public Nullable<bool> IMSInclude { get; set; }
        public Nullable<int> NonPublicDistrict { get; set; }
    }
}
