//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace <%=applicationshortname%>.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public Nullable<int> DefinitionStepID { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public string Question1 { get; set; }
        public Nullable<int> WizardValidationLength { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual DefinitionStep DefinitionStep { get; set; }
    }
}
