//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public string SchoolYear { get; set; }
        public short SchoolCode { get; set; }
        public Nullable<int> Location { get; set; }
        public string SchoolName { get; set; }
        public string SchoolShortName { get; set; }
        public Nullable<short> DistrictCode { get; set; }
        public Nullable<int> DepartmentKey { get; set; }
        public Nullable<int> DistrictKey { get; set; }
        public Nullable<int> LocationKey { get; set; }
        public string Title1 { get; set; }
        public Nullable<float> FRLunchPct { get; set; }
        public string SuplServices { get; set; }
        public string ChoiceEntry { get; set; }
        public string ChoiceWithdraw { get; set; }
        public string MultiDistrict { get; set; }
        public string NewAcctSch { get; set; }
        public string Accountability { get; set; }
        public string EdenInclude { get; set; }
        public string Charter { get; set; }
        public string Magnet { get; set; }
        public string Type { get; set; }
        public string Religious { get; set; }
        public Nullable<short> County { get; set; }
        public string UrbanArea { get; set; }
        public string Act { get; set; }
        public string EduLevel { get; set; }
        public string ProfileLevel { get; set; }
        public string HomeSchool { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string PhExtn { get; set; }
        public string Fax { get; set; }
        public Nullable<int> NcesAgencyID { get; set; }
        public Nullable<int> NcesPriorLEAID { get; set; }
        public string NcesSchID { get; set; }
        public string NcesPhone { get; set; }
        public Nullable<byte> NcesSchType { get; set; }
        public string NcesGradeSpan { get; set; }
        public Nullable<byte> NcesLocCode { get; set; }
        public Nullable<byte> NcesOpStatus { get; set; }
        public int SeqNum { get; set; }
        public string WebAddress { get; set; }
        public string Email { get; set; }
        public string DirectoryInclusion { get; set; }
        public string GradeSpan { get; set; }
        public int SortOrder { get; set; }
        public string RouterIP { get; set; }
        public string EdDirName { get; set; }
        public Nullable<byte> EmailHS { get; set; }
        public Nullable<byte> EmailMS { get; set; }
        public Nullable<byte> EmailES { get; set; }
        public string SLC { get; set; }
        public string ScienceKitsBilling { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string ChangeUser { get; set; }
        public string ChangeAction { get; set; }
        public string ProfileSchool { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string NCESCharter { get; set; }
        public Nullable<bool> IMSInclude { get; set; }
        public Nullable<int> EschoolBuilding { get; set; }
        public Nullable<int> NonPublicDistrict { get; set; }
    }
}
