//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WizardQuestion()
        {
            this.DemoQuestions = new HashSet<DemoQuestion>();
        }
    
        public int WizardQuestionID { get; set; }
        public Nullable<int> WizardDefinitionStepID { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public string WizardQuestion1 { get; set; }
        public Nullable<int> WizardValidationLength { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemoQuestion> DemoQuestions { get; set; }
        public virtual WizardDefinitionStep WizardDefinitionStep { get; set; }
    }
}
