//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace <%=applicationshortname%>.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WizardEntities : DbContext
    {
        public WizardEntities()
            : base("name=WizardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Definition> Definitions { get; set; }
        public virtual DbSet<DefinitionStep> DefinitionSteps { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
    }
}
